name: deploy-lab

on:
  workflow_dispatch:

env:
  TF_VAR_users: 

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      users: ${{ steps.get_users.outputs.users }}
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Get Users
      id: get_users
      run: |
        $(curl -k "https://www.moogleapi.com/api/v1/characters" --output json | jq -c ) > users.json
        # echo "TF_VAR_users=$users" >> $GITHUB_ENV
        # echo "users=$users" >> "$GITHUB_OUTPUT"
    - name: Upload Users
      uses: actions/upload-artifact@v3
      with:
        name: users
        path: users.json

  plan:
    name: TF Plan
    needs: Setup

    steps:
    - name: Download Users
      uses: actions/download-artifact@v3
      with:
        name: users
    - shell: bash
      run: |
        echo
        echo "cat users.json"
        echo 
