name: deploy-lab

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Get Users
      run: |
        curl -k "https://www.moogleapi.com/api/v1/characters" > users.json

    - name: Upload Users Artifact
      uses: actions/upload-artifact@v3
      with:
        name: users
        path: users.json

  terraform:
    name: Terraform
    needs: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Download Users
      uses: actions/download-artifact@v3
      with:
        name: users

    - name: TF Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6
        cli_config_credentials_hostname: 'app.terraform.io'
        cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

    - name: TF Init
      run: terraform init

    - name: TF Plan
      run: terraform plan

    # - name: TF Apply
    #   run: terraform apply

    - name: Simulate File Creation After Apply
      shell: bash
      run: echo [{'"username"':'"password"'}] > creds.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: creds
        path: creds.json

  export:
    name: Export
    needs: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "pizza-bot@somewhere.org"
        git config --global user.name "pizza-bot"

    - name: Download Creds
      uses: actions/download-artifact@v3
      with:
        name: creds

    - name: Check-in File
      run: |
        git add -A
        git commit -m "🍕"
        git push
