name: deploy-lab

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: Get Users
      run: |
        curl -k "https://www.moogleapi.com/api/v1/characters" > users.json

    - name: Upload Users
      uses: actions/upload-artifact@v3
      with:
        name: users
        path: users.json

  terraform:
    name: Terraform
    needs: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Download Users
      uses: actions/download-artifact@v3
      with:
        name: users

    - name: TF Setup
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6
        cli_config_credentials_hostname: 'app.terraform.io'
        cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

    - name: TF Init
      run: terraform init

    - name: TF Plan
      run: terraform plan
